main_tasks:
  core_configuraiton
  f5_configuration

sub_tasks:
  config_from_file
  config_from_command 

output_directory:
  output

config_file:
  src/configuration/f5_configuration.csv

core_networks:
  lab1:
    username: cisco
    password: cisco

  prod1:
    username: input username
    password: input password
    

