tasks:
  prechange_snapshot
  postchange_snapshot_and_diff_prechange_snapshot
  postchange_snapshot_and_diff_last_postchange_snapshot

output_directory:
  /output

result_folder_suffix:
  ChangeNumber

core_networks:
  lab1:
    username: cisco
    password: cisco

  prod1:
    username: input username
    password: input password
    
diff_organize_keywords:
  config interface routing bgp ospf routes

threads_number:
  6

pyats_learn_features:
  interface ospf

nxos_self_learn_commands:
  - show ip route vrf all
  - show interface brief

iosxe_self_learn_commands:
  - show ip interface brief
  - show ip route 
