main_tasks:
  core_validation_pyats
  core_validation_netmiko  
  aci_validation
  aci_search
  juniper_validation
  f5_validation
  fortinet_validation
  paloalto_validation

sub_tasks:
  prechange_snapshot
  postchange_snapshot_and_diff_prechange_snapshot
  postchange_snapshot_and_diff_last_postchange_snapshot

output_directory:
  output

testbed_directory:
  testbed

parsertemplate_direcotry:
  parsertemplate

result_folder_suffix:
  ChangeNumber

aci_list:
  lab1
  lab2
  prod1

core_networks:
  lab1:
    username: cisco
    password: cisco

  prod1:
    username: input username
    password: input password

aci_networks:
  lab1:
    hostname: 10.10.20.14
    username: admin
    password: C1sco12345

  lab2:
    hostname: 131.226.217.153
    username: admin
    password: "!v3G@!4@Y"

  prod1:
    hostname: input hostname
    username: input username
    password: input password
    
diff_organize_keywords:
  config interface routing bgp ospf routes

threads_number:
  6

pyats_learn_features:
  interface ospf

nxos_learn_commands:
  - show interface status
  - show interface brief

iosxe_learn_commands:
  - show ip interface brief
  - show inventory

f5_tmsh_learn_commands:
  - show net interface
  - show net route

fortinet_learn_commands:
  - get system session list
  - show firewall policy

fortinet_vdom_commands:
  - config vdom
  - edit root

aci_query_classes:
  validation_query:
    query_class_no_children: 
      topSystem ethpmPhysIf l1PhysIf lldpAdjEp fvRsPathAtt ospfAdjEp
      fvTenant l3extLNodeP l3extVirtualLIfP l3extRsDynPathAtt l3extRsPathL3OutAtt l3extMember l3extIp l3extLoopBackIfP fvAp fvSubnet 
      l3extSubnet l3extRsEctx vzEntry vzRsFiltAtt vzRsSubjFiltAtt fvATg l2extInstP fvRsSecInherited fvIp
      fabricNode
      #ospfIf fabricPod fabricNode l1PhysIf 
      # fvRsPathAtt
      #fvRsCEpToPathEp  fvEPg fabricPathGrp
    query_class_with_children: 
      # fvCtx vpcDom bgpPeerEntry fvnsVlanInstP
      fvCEp l3extOut fvCtx fvBD fvAEPg l3extInstP vzSubj l3extRsNodeL3OutAtt l3extLIfP bgpPeerP vzBrCP vzSubj vzFilter vpcDom actrlFlt bgpPeerEntry fvnsVlanInstP ipRouteP
    # query_loop_per_pod_node:
    #   actrlRule
    query_loop_per_tenant_vrf_dn:
      any
    query_loop_per_tenant_vrf_name:
      uribv4Route
    query_special_urls:
      # l3extOut: /api/mo/uni.json?query-target=subtree&target-subtree-class=l3extOut
      configSnapshot: /api/node/class/configSnapshot.json?query-target-filter=and(not(wcard(configSnapshot.dn,"__ui_")),wcard(configSnapshot.rootDn,"^(?!uni/tn-).*"))

  query_and_exit_keyword:
    None #l3extRsPathL3OutAtt fvIp #uribv4Route common:GREEN_VRF #fvATg

  endpoint_tracker_query:
    query_class_with_children:
      fvCEp